import type { InterestTag } from "src/features/interests/types";

export const interestOptions: InterestTag[] = [
  { id: "architektura", name: "Architektúra" },
  { id: "atletika", name: "Atletika" },
  { id: "badminton", name: "Badminton" },
  { id: "basketbal", name: "Basketbal" },
  { id: "beh", name: "Beh" },
  { id: "behanie-v-prirode", name: "Behanie v prírode" },
  { id: "bezky", name: "Bežky" },
  { id: "bicykel", name: "Bicykel" },
  { id: "bistra", name: "Bistrá" },
  { id: "biliard", name: "Biliard" },
  { id: "blogovanie", name: "Blogovanie" },
  { id: "bouldering", name: "Bouldering" },
  { id: "bojove-umenia", name: "Bojové umenia" },
  { id: "bowling", name: "Bowling" },
  { id: "box", name: "Box" },
  { id: "camping", name: "Camping" },
  { id: "cestovanie", name: "Cestovanie" },
  { id: "crossfit", name: "CrossFit" },
  { id: "cudzie-jazyky", name: "Cudzie jazyky" },
  { id: "caj", name: "Čaj" },
  { id: "dizajn", name: "Dizajn" },
  { id: "divadlo", name: "Divadlo" },
  { id: "dobrovolnictvo", name: "Dobrovoľníctvo" },
  { id: "domace-zvierata", name: "Domáce zvieratá" },
  { id: "doskovky", name: "Doskovky" },
  { id: "financie", name: "Financie" },
  { id: "fitko", name: "Fitko" },
  { id: "florbal", name: "Florbal" },
  { id: "frisbee", name: "Frisbee" },
  { id: "fotografia", name: "Fotografia" },
  { id: "futbal", name: "Futbal" },
  { id: "gitara", name: "Gitara" },
  { id: "golf", name: "Golf" },
  { id: "hadzana", name: "Hádzaná" },
  { id: "hokej", name: "Hokej" },
  { id: "hudba", name: "Hudba" },
  { id: "hry", name: "Hry" },
  { id: "jedlo", name: "Jedlo" },
  { id: "joga", name: "Joga" },
  { id: "judo", name: "Judo" },
  { id: "kajak", name: "Kajak" },
  { id: "kalistenika", name: "Kalistenika" },
  { id: "kava", name: "Káva" },
  { id: "karate", name: "Karate" },
  { id: "kickbox", name: "Kickbox" },
  { id: "kino", name: "Kino" },
  { id: "knihy", name: "Knihy" },
  { id: "koncerty", name: "Koncerty" },
  { id: "korculovanie", name: "Korčuľovanie" },
  { id: "kreativne-pisanie", name: "Kreatívne písanie" },
  { id: "kreslenie", name: "Kreslenie" },
  { id: "kvizy", name: "Kvízy" },
  { id: "lezenie", name: "Lezenie" },
  { id: "lyzovanie", name: "Lyžovanie" },
  { id: "malovanie", name: "Maľovanie" },
  { id: "meditacia", name: "Meditácia" },
  { id: "mma", name: "MMA" },
  { id: "motorky", name: "Motorky" },
  { id: "muay-thai", name: "Muay Thai" },
  { id: "muzea", name: "Múzeá" },
  { id: "nakupovanie", name: "Nakupovanie" },
  { id: "nocne-prechadzky", name: "Nočné prechádzky" },
  { id: "padel", name: "Padel" },
  { id: "paddleboard", name: "Paddleboard" },
  { id: "parkour", name: "Parkour" },
  { id: "pecenie", name: "Pečenie" },
  { id: "pikniky", name: "Pikniky" },
  { id: "pilates", name: "Pilates" },
  { id: "plavanie", name: "Plávanie" },
  { id: "podcasty", name: "Podcasty" },
  { id: "politika", name: "Politika" },
  { id: "posilnovanie", name: "Posilňovanie" },
  { id: "powerlifting", name: "Powerlifting" },
  { id: "programovanie", name: "Programovanie" },
  { id: "psychologia", name: "Psychológia" },
  { id: "rugby", name: "Rugby" },
  { id: "rucne-prace", name: "Ručné práce" },
  { id: "sauna", name: "Sauna" },
  { id: "skateboarding", name: "Skateboarding" },
  { id: "skialp", name: "Skialp" },
  { id: "snowboard", name: "Snowboard" },
  { id: "spev", name: "Spev" },
  { id: "spolocenske-hry", name: "Spoločenské hry" },
  { id: "squash", name: "Squash" },
  { id: "standup", name: "Stand-up" },
  { id: "stolny-tenis", name: "Stolný tenis" },
  { id: "surfovanie", name: "Surfovanie" },
  { id: "tanec", name: "Tanec" },
  { id: "taekwondo", name: "Taekwondo" },
  { id: "technologie", name: "Technológie" },
  { id: "tenis", name: "Tenis" },
  { id: "triatlon", name: "Triatlon" },
  { id: "turistika", name: "Turistika" },
  { id: "turisticke-chaty", name: "Turistické chaty" },
  { id: "umenie", name: "Umenie" },
  { id: "varenie", name: "Varenie" },
  { id: "wellness", name: "Wellness" },
  { id: "vino", name: "Víno" },
  { id: "volejbal", name: "Volejbal" },
  { id: "vodne-polo", name: "Vodné pólo" },
  { id: "veslovanie", name: "Veslovanie" },
  { id: "vzpieranie", name: "Vzpieranie" },
  { id: "vzdelavanie", name: "Vzdelávanie" },
  { id: "vystavy", name: "Výstavy" },
  { id: "vylety", name: "Výlety" },
  { id: "zapasenie", name: "Zápasenie" },
  { id: "zahrada", name: "Záhrada" },
  { id: "ziva-hudba", name: "Živá hudba" },
] as const;
