export const discoveryFilterStyles = {
  filterSummary: {
    align: "center",
    display: "grid",
    flex: 1,
    gridTemplateColumns:
      "minmax(0, 1.1fr) 13px minmax(42px, 0.48fr) 13px minmax(58px, 0.72fr) 13px minmax(45px, 0.45fr)",
    minW: 0,
  },
  filterSegment: {
    display: "grid",
    gap: "2px",
    minW: 0,
    overflow: "hidden",
    px: "3px",
    color: "app.text",
    fontSize: "sm",
    fontWeight: "semibold",
    lineHeight: 1.25,
    textAlign: "left",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    _hover: {
      color: "app.base",
    },
  },
  filterSegmentLabel: {
    color: "rgba(53, 87, 45, 0.62)",
    fontSize: "10px",
    fontWeight: "black",
    lineHeight: 1,
    textTransform: "uppercase",
  },
  filterSegmentValue: {
    display: "block",
    minW: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  filterDivider: {
    justifySelf: "center",
    w: "1px",
    h: "34px",
    bg: "rgba(53, 87, 45, 0.24)",
  },
  filterEditorWrap: {
    position: "relative",
    flex: 1,
    minW: 0,
  },
  filterEditorGrid: {
    display: "grid",
    alignItems: "center",
    gridTemplateColumns: "38px minmax(0, 1fr) 38px",
    gap: "6px",
  },
  filterAgeEditorGrid: {
    display: "grid",
    alignItems: "center",
    gridTemplateColumns: "28px minmax(0, 1fr) minmax(0, 1fr) 38px",
    gap: "6px",
  },
  filterGenderEditor: {
    align: "center",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 38px",
    gap: "6px",
  },
  inlineGenderOptions: {
    flexWrap: "wrap",
    gap: "7px",
  },
  filterEditorLabel: {
    color: "rgba(53, 87, 45, 0.62)",
    fontSize: "10px",
    fontWeight: "black",
    lineHeight: 1,
    textTransform: "uppercase",
  },
  inlineInput: {
    h: "38px",
    px: "10px",
    borderRadius: "999px",
    fontSize: "sm",
  },
  confirmButton: {
    display: "grid",
    placeItems: "center",
    boxSize: "38px",
    minW: "38px",
    border: "1px solid",
    borderColor: "rgba(53, 87, 45, 0.18)",
    borderRadius: "999px",
    bg: "app.white",
    color: "app.base",
    _hover: { bg: "app.bgAux" },
    _active: { bg: "app.bgAux" },
  },
  locationOptions: {
    position: "absolute",
    top: "calc(100% + 8px)",
    left: 0,
    right: 0,
    zIndex: 50,
    maxH: "196px",
    overflowY: "auto",
    border: "1px solid",
    borderColor: "rgba(53, 87, 45, 0.18)",
    borderRadius: "18px",
    bg: "app.white",
    boxShadow: "0 14px 32px rgba(53, 87, 45, 0.14)",
    p: "6px",
  },
  locationOption: {
    h: "auto",
    minH: "38px",
    w: "100%",
    justifyContent: "flex-start",
    px: "10px",
    py: "8px",
    borderRadius: "999px",
    color: "app.text",
    fontSize: "sm",
    fontWeight: "bold",
    textAlign: "left",
    whiteSpace: "normal",
    _hover: { bg: "app.bgAux", color: "app.text" },
    _focusVisible: {
      bg: "app.bgAux",
      boxShadow: "0 0 0 2px rgba(79, 131, 68, 0.22)",
      color: "app.text",
    },
  },
  inlineLoaderWrap: {
    h: "38px",
    w: "38px",
  },
  inlineLoader: {
    color: "app.base",
    opacity: 0.72,
    speed: "0.7s",
    thickness: "2px",
    size: "sm",
  },
} as const;
