export const topBarStyles = {
  iconButton: {
    display: "grid",
    placeItems: "center",
    boxSize: "42px",
    minW: "42px",
    border: "1px solid",
    borderColor: "app.white",
    borderRadius: "999px",
    color: "app.base",
    bg: "app.white",
    _hover: { bg: "app.white" },
    _active: { bg: "app.white" },
    _disabled: {
      bg: "app.white",
      borderColor: "app.white",
      cursor: "default",
      opacity: 1,
      _hover: { bg: "app.white" },
    },
  },
  menuList: {
    minW: "148px",
    mt: "8px",
    border: "1px solid",
    borderColor: "app.text",
    borderRadius: "8px",
    boxShadow: "0 16px 34px rgba(53, 87, 45, 0.18)",
    overflow: "hidden",
    p: 0,
  },
  menuItem: {
    alignItems: "center",
    color: "app.text",
    display: "flex",
    fontSize: "sm",
    fontWeight: "extrabold",
    gap: "12px",
    px: "16px",
    py: "12px",
    _focus: { bg: "rgba(79, 131, 68, 0.1)" },
    _hover: { bg: "rgba(79, 131, 68, 0.1)" },
  },
  menuItemIcon: {
    boxSize: "21px",
    color: "app.baseDark",
    flexShrink: 0,
  },
  brand: {
    align: "center",
    gap: { base: "11px", sm: "12px" },
    h: "44px",
    cursor: "pointer",
    textDecoration: "none",
    _hover: {
      textDecoration: "none",
    },
  },
  brandMark: {
    width: "60px",
    height: "42px",
    align: "center",
    bg: "app.white",
    borderRadius: "999px",
    justify: "center",
  },
  brandText: {
    mt: "2px",
    ml: "-2px",
    color: "app.white",
    fontFamily:
      '"Comic Sans MS", "Comic Neue", "Trebuchet MS", Verdana, sans-serif',
    fontSize: { base: "21px", sm: "24px" },
    fontWeight: "normal",
    lineHeight: 1,
    letterSpacing: "3px",
    textShadow: "none",
    transform: "scaleX(0.88)",
    transformOrigin: "left center",
    sx: {
      WebkitTextStroke: "0.5px var(--chakra-colors-app-white)",
      paintOrder: "stroke fill",
    },
  },
  matchIconWrap: {
    position: "relative",
    align: "center",
    justify: "center",
    boxSize: "31px",
  },
  matchIconCount: {
    position: "absolute",
    top: "-5px",
    right: "-8px",
    alignItems: "center",
    justifyContent: "center",
    minW: "20px",
    h: "20px",
    px: "4px",
    border: "2px solid",
    borderColor: "app.white",
    borderRadius: "999px",
    bg: "#F97316",
    color: "app.white",
    fontSize: "11px",
    fontWeight: "black",
    lineHeight: 1,
    boxShadow: "0 1px 4px rgba(53, 87, 45, 0.28)",
  },
} as const;
